dist: trusty
language: php
sudo: false
php:
- 5.6
- 7.0
- 7.2
cache:
  directories:
  - "$HOME/.composer/cache"
install:
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}"
  > auth.json
- composer install --prefer-dist
script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit
