dist: trusty
language: php
sudo: false
php:
- 5.6
- 7.0
cache:
  directories:
  - "$HOME/.composer/cache"
install:
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}"
  > auth.json
- composer install --prefer-dist
script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit
env:
  global:
  - secure: Hh30LAXVy7r28buBiHx1iXxSNnKJS2vSJHLqL1Y6j7QFJ8ljeZmt3DpqDEepnGLJYBiFGa03kc+evHTm8+CbwVZKWACrSRtlUrrrDFeOVJKM7uXV/lzwWt8TpgRanRk9efUdifwtPDxq+Q1YNCnNozPExfKk0fJxf0XjMdPxyl+cCXAf2eP1eWwsfAH2R829crByfSSnhIZMqV44PX12TJDn3pfNqgP1DAuTrEX37EIH+pq02r1dT666TYth9Z3xxmvI0itHpZRMrbZQG4cFJspDmMqMd3PVKvJOiLUC+/CwezNKXKgWfcRT2rccsgPapxszGYAV9xrim84IuapcK3lnO2nGm33lAYWILcKltiDIHakpgsUnwh9XXOKpROYG42RdPj0XEkRfrsrYoYYWMQvbHasjHgQ3fCajHPpF0GK8D7Jx+4UVFJQvNC+MqK8Lmp47jzrb3Wn8FHaGqd5qXAwDCokQVzB1SPzayHaMYTeQOrHEJNwsxHQBxpO8tz8/6W/cojq4XunayqP/e0pGnRvnPP3E2yw1HE7oO5ng2U/QBou8sT0p9p3op/4UK9wKcQWZEE1wPvQgLP2G/ZL1p6+yd9x+u5GnoW2M5iQxu6dktedw93sl/BdrxfnM6Rnmgun1bjM0Ho2qPUmRntKdjCAjK5tGQILIFYI/TWBmIEo=
  - secure: oxHh63n6YBSSUENmw73l82m3nKP1sLqTcqxVDNa7U54Ux+60qeksh4Zmw8XkpENUyOSUfUXNtiMzCdLvJCQB56v4yPqh5gPYHHzpbFasApUjNdx9Nv6HxIlbg3f4oBwI2auvBEhc1uz7ZyamQzHQmX6jyYad9Ykx5onlxNsvpFpMV1f5Nl7QWj7wfCPD3asOsCbE34dyaJIpPRj6barXV38r9KM6v1PC3kn1ZCWvAuwrbsw0HhOIMurYocKgZZT28VWJIW7FzKV41carQJof/7k/g+m/N3iznWYP5NRWTvEW8iaNPlg9CDn1bQ34F2kw7xz754k0DE8bP194ixTPl7G0ncsIOeQpqE1+AQddqCGEHHHfh6/e9rdsQ2OWwmIvxxlmOcdmk/SWAgtZ7ZqLyVO74DmyiRbOtUic+d0pxInN2ffnXiI3c/BvGphcqSosRmsHxxgo3RtmFMdKgiqOqqk6NNna68EjhhvYSxWrrjhkiOr2NTR1OEKRPY6gvPcr+ASdeuUTuHRFwGODWx7ZN5qiCFAvKB8iWndszYZLx4o6kM54rBfTS8+k7ukoqr14uhuftkwsZqKTtWOANZouIwVsXL69FAWHvgLcWNKj8CklXrUqDUAWDgqzNeadjxaELLlusHf7bJ6nfxhPY5TmbXTGvS+AsKGW3F4t4BNs6bQ=
notifications:
  slack:
    secure: LxHaxvaFv/NXI5vxGDVe151ve+C9ss/irbEeRVuBUzmv33Gf3xqM4X1UiZvJUb4ikM5f4IhKsRy9tl4c32mBXKemPlhL0CueyeCy5x674twrtaHRCu3rEPwt0Zg4mOwZz3Ljv1wGjL1kgnq4Eb/j1+cgxqxjyt1FqvdW67bKhDAIw0h0PnBHFOiSyjYyUwBapPFPNO6YPli0iofj1x+pQAtghoBMAOOhe0T1BA+e++OWhnnVo4toePtBluW/ClmjNTOrQdnBHOovfvCYdi3E5qPIwHMy1lPv3uOe1CoKOWrFmdSZxJXjKDUGwGDNCnRSJm1g5qx+TURvkZ7KwJ9SiFd9vtf9QmzLQonkYH7KjIqq9ez5LIRfZq30RUkpUiFa8VUtmdjcijA7HYZ9CHo789sAFRXHlUqnihvWS0TTLubWcW77tLf+iBFcPGp0zkY6dMjy4EZEPPs+v5fF4tVisI8/I6G/wvQnZrBC37Naxvmsle7fuHRltqkCS03etlIxtjpyJFwyzj3iTL/sPm+j4v1dGKPErbnwLnAXn1YesOKUBKETYEdFcL21oXBUX8R2Ntt2r84ECAOF87eiW1op3uxeETIMy/sUB81IlC9Eu6kozBLRXB2+csSMoDR4qU/q2MCNLbH2Zv0MzohhiLonBoKRjMgn2p3V/FrK8lSf9Ho=
